# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='age',
            field=models.IntegerField(),
        ),
    ]
