# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20170422_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
