# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20170501_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='seq',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='seq1',
        ),
    ]
