# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20170501_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
