# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_auto_20170501_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlikes',
            name='sign',
            field=models.NullBooleanField(),
        ),
    ]
