# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_questionlikes_sign'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionlikes',
            table=None,
        ),
    ]
