# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20170501_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answerlikes',
            old_name='post',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='answerlikes',
            name='sign',
            field=models.NullBooleanField(),
        ),
        migrations.AlterUniqueTogether(
            name='answerlikes',
            unique_together=set([('author', 'answer')]),
        ),
    ]
