# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_auto_20170501_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
