# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20170508_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='avatar',
            field=models.ImageField(default='user_avatar.jpg', upload_to='avatar/%Y'),
        ),
    ]
