# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_question_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user_avatar/std_user_avatar.png', upload_to='user_avatar/%Y'),
        ),
    ]
