# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_auto_20170603_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
