# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_answer_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='check',
            new_name='checked',
        ),
    ]
